name: CRIME
version: 1.6
date: 2022-03-17
description: |
    A GAP Package to Calculate Group Cohomology and Massey Products

authors:
    - name: Marcus Bishop
      url: http://math.uic.edu/~marcus

maintainers:
    - name: The GAP Team
      url: mailto:support@gap-system.org

GAP: ">=4.9"

www: https://gap-packages.github.io/crime/
readme: README.md
packageinfo: https://gap-packages.github.io/crime/PackageInfo.g

downloads:
    - name: .tar.gz
      url: https://github.com/gap-packages/crime/releases/download/v1.6/crime-1.6.tar.gz

abstract: |
    This package computes the cohomology rings of finite p-groups, induced maps, and Massey products.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    cohomology.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>BT22</span>]   <b class='BibAuthor'>Bishop, M. and GAP Team, T.</b>,
     <i class='BibTitle'>CRIME, A GAP Package to Calculate Group Cohomology and Massey Products,
             Version 1.6</i>
     (<span class='BibYear'>2022</span>)<br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="https://gap-packages.github.io/crime/">https://gap-packages.github.io/crime/</a></span>.
    </p>
    

bibtex: |
    @misc{ CRIME1.6,
      author =           {Bishop, M. and GAP Team, T.},
      title =            {{CRIME},  A  GAP Package to Calculate Group Cohomology
                          and Massey Products, {V}ersion 1.6},
      month =            {Mar},
      year =             {2022},
      note =             {Refereed GAP package},
      howpublished =     {\href          {https://gap-packages.github.io/crime/}
                          {\texttt{https://gap-packages.github.io/}\discretionary
                          {}{}{}\texttt{crime/}}},
      keywords =         {cohomology},
      printedkey =       {BT22}
    }

