name: CRIME
version: 1.4
date: 2011-06-01
description: |
    A GAP Package to Calculate Group Cohomology and Massey Products

authors:
    - name: Marcus Bishop
      url: http://math.uic.edu/~marcus

maintainers:
    - name: Marcus Bishop
      url: http://math.uic.edu/~marcus

GAP: ">=4.4"

www: http://math.uic.edu/~marcus/Crime
readme: README
packageinfo: http://math.uic.edu/~marcus/Crime/PackageInfo.g

downloads:
    - name: .tar.gz
      url: http://math.uic.edu/~marcus/Crime/crime-1.4.tar.gz

abstract: |
    This package computes the cohomology rings of finite p-groups, induced maps, and Massey products.

status: accepted
doc-html: doc/chap0.html
doc-pdf: doc/manual.pdf
keywords: |
    cohomology.
citeas: |
    <p class='BibEntry'>
    [<span class='BibKey'>Bis</span>]   <b class='BibAuthor'>Bishop, M.</b>,
     <i class='BibTitle'>CRIME, A GAP Package to Calculate Group Cohomology and Massey Products,
             Version 1.4</i><br />
    (<span class='BibNote'>Refereed GAP package</span>),
    <span class='BibHowpublished'><a href="http://math.uic.edu/~marcus/Crime">http://math.uic.edu/~marcus/Crime</a></span>.
    </p>
    

bibtex: |
    @misc{ CRIME1.4,
      author =           {Bishop, M.},
      title =            {{CRIME}, A GAP Package to Calculate Group Cohomology and Massey Products, {V}ersion 1.4},
      note =             {Refereed GAP package},
      howpublished =     {\href   {http://math.uic.edu/~marcus/Crime}   {\texttt{http://math.uic.edu/}\discretionary   {}{}{}\texttt{\texttt{\symbol{126}}marcus/}\discretionary
                          {}{}{}\texttt{Crime}}},
      keywords =         {cohomology},
      printedkey =       {Bis}
    }

